# Generated by Django 5.0.1 on 2024-01-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0002_constructionpost_delete_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionpost',
            name='location',
            field=models.CharField(default=1, max_length=2200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constructionpost',
            name='price',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
