# Generated by Django 5.0.1 on 2024-01-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0003_constructionpost_location_constructionpost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200)),
                ('worker_position', models.CharField(max_length=200)),
                ('worker_description', models.TextField()),
                ('worker_img', models.ImageField(upload_to='images')),
                ('slug', models.SlugField(max_length=25)),
            ],
        ),
    ]
