# Generated by Django 5.0.1 on 2024-01-31 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0007_rename_teams_teamspost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Of_DirectorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_of_director_name', models.CharField(max_length=200)),
                ('board_of_director_position', models.CharField(max_length=200)),
                ('board_of_director_description', models.TextField()),
                ('board_of_director_img', models.ImageField(upload_to='images_dir')),
                ('slug', models.SlugField(max_length=25)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
