# Generated by Django 5.0.1 on 2024-02-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0008_board_of_directorpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionpost',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RenameField(
            model_name='constructionpost',
            old_name='publish_date1',
            new_name='publish_date',
        ),
    ]
