# Generated by Django 5.0.1 on 2024-02-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0009_alter_constructionpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_of_directorpost',
            name='board_of_director_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='board_of_directorpost',
            name='board_of_director_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constructionpost',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constructionpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teamspost',
            name='worker_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teamspost',
            name='worker_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
