# Generated by Django 5.0.1 on 2024-02-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0013_constructionpost_qm_constructionpost_rent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionpost',
            old_name='qm',
            new_name='Sqm',
        ),
    ]
