# Generated by Django 5.0.1 on 2024-02-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0014_rename_qm_constructionpost_sqm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionpost',
            old_name='Sqm',
            new_name='sqm',
        ),
    ]
