# Generated by Django 5.0.1 on 2024-02-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0015_rename_sqm_constructionpost_sqm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionpost',
            name='sqm',
        ),
    ]
