# Generated by Django 5.0.1 on 2024-02-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0019_remove_constructionpost_bedroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('state', models.FloatField()),
                ('contry', models.FloatField()),
            ],
        ),
    ]
