# Generated by Django 5.0.1 on 2024-02-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0020_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='contry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
