# Generated by Django 5.0.1 on 2024-02-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0021_alter_location_contry_alter_location_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='contry',
            new_name='country',
        ),
    ]
