# Generated by Django 5.0.1 on 2024-02-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0023_search_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionpost',
            name='search',
            field=models.ManyToManyField(to='josepdam.search'),
        ),
    ]
