# Generated by Django 5.0.1 on 2024-02-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0024_constructionpost_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionpost',
            name='search',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
