# Generated by Django 5.0.1 on 2024-02-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0029_construction2_delete_constructionpost2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='construction2',
            old_name='img',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='construction2',
            old_name='title',
            new_name='title1',
        ),
    ]
