# Generated by Django 5.0.1 on 2024-02-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0030_rename_img_construction2_image1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Construction2',
        ),
    ]
