# Generated by Django 5.0.1 on 2024-02-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0032_secondconstruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondconstruction',
            name='image1',
            field=models.ImageField(upload_to='image3/'),
        ),
    ]
