# Generated by Django 5.0.1 on 2024-03-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0033_alter_secondconstruction_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondconstruction',
            name='details',
        ),
        migrations.RemoveField(
            model_name='secondconstruction',
            name='size',
        ),
    ]
