# Generated by Django 5.0.1 on 2024-03-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0034_remove_secondconstruction_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondconstruction',
            name='location',
        ),
    ]
