# Generated by Django 5.0.1 on 2024-03-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0035_remove_secondconstruction_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionpost',
            name='price',
        ),
        migrations.AddField(
            model_name='secondconstruction',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondconstruction',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondconstruction',
            name='rent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secondconstruction',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
