# Generated by Django 5.0.1 on 2024-03-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0037_remove_secondconstruction_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondconstruction',
            name='details',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secondconstruction',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='secondconstruction',
            name='rent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
