# Generated by Django 5.0.1 on 2024-03-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0038_alter_secondconstruction_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionpost',
            name='rent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
