# Generated by Django 5.0.1 on 2024-03-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0039_alter_constructionpost_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionpost',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
