# Generated by Django 5.0.1 on 2024-03-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0042_commentmodel_remove_constructionpost_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionpost',
            name='comments',
        ),
    ]
