# Generated by Django 5.0.1 on 2024-03-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0046_alter_comment_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
