# Generated by Django 5.0.1 on 2024-03-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0047_delete_commentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
