# Generated by Django 5.0.1 on 2024-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josepdam', '0048_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMissionVisionCoreValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=900, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
